spring:
  batch:
    job:
      enabled: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/rootChangelog.xml
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password:
    #    url: jdbc:h2:tcp://localhost:9092/~/h2/bookkeeperdb
    url: jdbc:h2:mem:testdb
  data:
    mongodb:
      database: mongo-db-old
      host: localhost
      port: 27017
mongock:
#  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.dartilla.bookkeeper.mms.mongock.changelog
app:
  chunkSize: 5