spring:
  datasource:
    url: jdbc:h2:mem:testdb
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/rootChangelog.xml
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties.hibernate:
      order_inserts: true
      jdbc:
        batch_size: 5
    show-sql: false
management:
  endpoints:
    web:
      exposure:
        include: "health, metrics, logfile, loggers"
  endpoint:
    health:
      show-details: always
    logfile:
      external-file: target/logs/heap.log

---
spring:
  profiles: localh2
  datasource:
    url: jdbc:h2:${h2path}
